name: thuongmaidientu
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.3
  cupertino_icons: ^1.0.8
  video_player: ^2.9.2
  image_picker: ^1.1.2
  permission_handler: ^11.1.0
  file_picker: ^10.1.9
  get_it: ^8.0.3
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  easy_localization: ^3.0.7+1
  overlay_support: ^2.1.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  loading_animation_widget: ^1.3.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  flutter_chat_core: ^2.0.0
  flutter_chat_ui: ^2.0.0
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.2.1
  dotted_border: ^3.0.1
  supabase_flutter: ^2.9.1
  uuid: ^4.5.1
  dropdown_search: ^6.0.2
  firebase_core_web: ^2.24.1
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.3.1
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  flutter_paypal_payment: ^1.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - .env
    - assets/logo/
    - assets/svg/
    - assets/translations/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
